spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dogslogsdb}
    username: ${SPRING_DATASOURCE_USERNAME:dogslogsuser}
    password: ${SPRING_DATASOURCE_PASSWORD:exo9-postgres-2026}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
